steps:
  # Build the container image
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['clean','install','-PbuildDocker']
  # Tagging
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', 'asia-northeast3-docker.pkg.dev/hyunyoung-01-368306/gcpzg/spring-petclinic-api-gateway', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/spring-petclinic-api-gateway:$SHORT_SHA']
  # Push the container image to Artifact Registry
images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/spring-petclinic-api-gateway:$SHORT_SHA'
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/spring-petclinic-api-gateway:$SHORT_SHA' ]

# Build Logging
logsBucket: 'cloud_logs9'
options:
  logging: GCS_ONLY





#    - name: 'gcr.io/cloud-builders/docker'
#      args: [ 'push', 'asia-northeast3-docker.pkg.dev/hyunyoung-01-368306/gcpzg/spring-petclinic-api-gateway' ]